package kaszucar.model;
// Generated 15 mars 2016 00:08:54 by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public")
public class Address implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  private int idAddress;
  private String address;
  private String complementAddress;
  private Integer postalCode;
  private String country;
  private Set<Users> userses = new HashSet<Users>(0);

  public Address() {}


  public Address(int idAddress) {
    this.idAddress = idAddress;
  }

  public Address(int idAddress, String address, String complementAddress, Integer postalCode,
      String country, Set<Users> userses) {
    this.idAddress = idAddress;
    this.address = address;
    this.complementAddress = complementAddress;
    this.postalCode = postalCode;
    this.country = country;
    this.userses = userses;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id_address", unique = true, nullable = false)
  public int getIdAddress() {
    return this.idAddress;
  }

  public void setIdAddress(int idAddress) {
    this.idAddress = idAddress;
  }


  @Column(name = "address", length = 1024)
  public String getAddress() {
    return this.address;
  }

  public void setAddress(String address) {
    this.address = address;
  }


  @Column(name = "complement_address", length = 1024)
  public String getComplementAddress() {
    return this.complementAddress;
  }

  public void setComplementAddress(String complementAddress) {
    this.complementAddress = complementAddress;
  }


  @Column(name = "postal_code")
  public Integer getPostalCode() {
    return this.postalCode;
  }

  public void setPostalCode(Integer postalCode) {
    this.postalCode = postalCode;
  }


  @Column(name = "country")
  public String getCountry() {
    return this.country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
  public Set<Users> getUserses() {
    return this.userses;
  }

  public void setUserses(Set<Users> userses) {
    this.userses = userses;
  }



}


