package kaszucar.model;
// Generated 11 f�vr. 2016 09:50:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cars generated by hbm2java
 */
@Entity
@Table(name = "cars", schema = "public")
public class Cars implements java.io.Serializable {

	private int idCars;
	private String brand;
	private String model;
	private String comfort;
	private String color;

	public Cars() {
	}

	public Cars(int idCars, String brand, String model) {
		this.idCars = idCars;
		this.brand = brand;
		this.model = model;
	}

	public Cars(int idCars, String brand, String model, String comfort, String color) {
		this.idCars = idCars;
		this.brand = brand;
		this.model = model;
		this.comfort = comfort;
		this.color = color;
	}

	@Id

	@Column(name = "id_cars", unique = true, nullable = false)
	public int getIdCars() {
		return this.idCars;
	}

	public void setIdCars(int idCars) {
		this.idCars = idCars;
	}

	@Column(name = "brand", nullable = false)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "model", nullable = false)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "comfort", length = 45)
	public String getComfort() {
		return this.comfort;
	}

	public void setComfort(String comfort) {
		this.comfort = comfort;
	}

	@Column(name = "color", length = 45)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
