package kaszucar.model;
// Generated 15 mars 2016 00:08:54 by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cars generated by hbm2java
 */
@Entity
@Table(name = "cars", schema = "public")
public class Cars implements java.io.Serializable {

  private static final long serialVersionUID = 1L;

  private int idCars;
  private String brand;
  private String model;
  private String comfort;
  private String color;
  private Set<Covoiturage> covoiturages = new HashSet<Covoiturage>(0);
  private Set<UsersHasCars> usersHasCarses = new HashSet<UsersHasCars>(0);

  public Cars() {}


  public Cars(int idCars, String brand, String model, String comfort, String color) {
    this.idCars = idCars;
    this.brand = brand;
    this.model = model;
    this.comfort = comfort;
    this.color = color;
  }

  public Cars(int idCars, String brand, String model, String comfort, String color,
      Set<Covoiturage> covoiturages, Set<UsersHasCars> usersHasCarses) {
    this.idCars = idCars;
    this.brand = brand;
    this.model = model;
    this.comfort = comfort;
    this.color = color;
    this.covoiturages = covoiturages;
    this.usersHasCarses = usersHasCarses;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id_cars", unique = true, nullable = false)
  public int getIdCars() {
    return this.idCars;
  }

  public void setIdCars(int idCars) {
    this.idCars = idCars;
  }


  @Column(name = "brand", nullable = false)
  public String getBrand() {
    return this.brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }


  @Column(name = "model", nullable = false)
  public String getModel() {
    return this.model;
  }

  public void setModel(String model) {
    this.model = model;
  }


  @Column(name = "comfort", nullable = false, length = 45)
  public String getComfort() {
    return this.comfort;
  }

  public void setComfort(String comfort) {
    this.comfort = comfort;
  }


  @Column(name = "color", nullable = false, length = 45)
  public String getColor() {
    return this.color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "cars")
  public Set<Covoiturage> getCovoiturages() {
    return this.covoiturages;
  }

  public void setCovoiturages(Set<Covoiturage> covoiturages) {
    this.covoiturages = covoiturages;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "cars")
  public Set<UsersHasCars> getUsersHasCarses() {
    return this.usersHasCarses;
  }

  public void setUsersHasCarses(Set<UsersHasCars> usersHasCarses) {
    this.usersHasCarses = usersHasCarses;
  }



}


