package kaszucar.model;
// Generated 11 f�vr. 2016 09:50:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CityWaypoints generated by hbm2java
 */
@Entity
@Table(name = "city_waypoints", schema = "public")
public class CityWaypoints implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCityStop;
	private int idCovoiturage;
	private String cityWaypoints;
	private Short orderWaypoints;

	public CityWaypoints() {
	}

	public CityWaypoints(int idCityStop, int idCovoiturage) {
		this.idCityStop = idCityStop;
		this.idCovoiturage = idCovoiturage;
	}

	public CityWaypoints(int idCityStop, int idCovoiturage, String cityWaypoints, Short orderWaypoints) {
		this.idCityStop = idCityStop;
		this.idCovoiturage = idCovoiturage;
		this.cityWaypoints = cityWaypoints;
		this.orderWaypoints = orderWaypoints;
	}

	@Id

	@Column(name = "id_city_stop", unique = true, nullable = false)
	public int getIdCityStop() {
		return this.idCityStop;
	}

	public void setIdCityStop(int idCityStop) {
		this.idCityStop = idCityStop;
	}

	@Column(name = "id_covoiturage", nullable = false)
	public int getIdCovoiturage() {
		return this.idCovoiturage;
	}

	public void setIdCovoiturage(int idCovoiturage) {
		this.idCovoiturage = idCovoiturage;
	}

	@Column(name = "city_waypoints")
	public String getCityWaypoints() {
		return this.cityWaypoints;
	}

	public void setCityWaypoints(String cityWaypoints) {
		this.cityWaypoints = cityWaypoints;
	}

	@Column(name = "order_waypoints")
	public Short getOrderWaypoints() {
		return this.orderWaypoints;
	}

	public void setOrderWaypoints(Short orderWaypoints) {
		this.orderWaypoints = orderWaypoints;
	}

}
