package kaszucar.model;
// Generated 4 févr. 2016 18:26:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CityStopId generated by hbm2java
 */
@Embeddable
public class CityStopId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCityStop;
	private int idCity;
	private int idCovoiturage;

	public CityStopId() {
	}

	public CityStopId(int idCityStop, int idCity, int idCovoiturage) {
		this.idCityStop = idCityStop;
		this.idCity = idCity;
		this.idCovoiturage = idCovoiturage;
	}

	@Column(name = "id_city_stop", nullable = false)
	public int getIdCityStop() {
		return this.idCityStop;
	}

	public void setIdCityStop(int idCityStop) {
		this.idCityStop = idCityStop;
	}

	@Column(name = "id_city", nullable = false)
	public int getIdCity() {
		return this.idCity;
	}

	public void setIdCity(int idCity) {
		this.idCity = idCity;
	}

	@Column(name = "id_covoiturage", nullable = false)
	public int getIdCovoiturage() {
		return this.idCovoiturage;
	}

	public void setIdCovoiturage(int idCovoiturage) {
		this.idCovoiturage = idCovoiturage;
	}

	public boolean equals(Object other) {
		if ((this == other)) return true;
		if ((other == null)) return false;
		if (!(other instanceof CityStopId)) return false;
		CityStopId castOther = (CityStopId) other;

		return (this.getIdCityStop() == castOther.getIdCityStop())
				&& (this.getIdCity() == castOther.getIdCity())
				&& (this.getIdCovoiturage() == castOther.getIdCovoiturage());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCityStop();
		result = 37 * result + this.getIdCity();
		result = 37 * result + this.getIdCovoiturage();
		return result;
	}

}
