package kaszucar.model;
// Generated 4 févr. 2016 18:26:01 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Covoiturage generated by hbm2java
 */
@Entity
@Table(name = "covoiturage", schema = "public")
public class Covoiturage implements java.io.Serializable {

	private CovoiturageId id;
	private Date dateFirstTrip;
	private Date dateReturnTrip;
	private int idCityFrom;
	private int idCityTo;
	private String description;
	private short price;
	private Integer idCars;
	private short sitNumber;
	private String sizeOfLuggage;

	public Covoiturage() {
	}

	public Covoiturage(CovoiturageId id, Date dateReturnTrip, int idCityFrom, int idCityTo, short price, short sitNumber, String sizeOfLuggage) {
		this.id = id;
		this.dateReturnTrip = dateReturnTrip;
		this.idCityFrom = idCityFrom;
		this.idCityTo = idCityTo;
		this.price = price;
		this.sitNumber = sitNumber;
		this.sizeOfLuggage = sizeOfLuggage;
	}

	public Covoiturage(CovoiturageId id, Date dateFirstTrip, Date dateReturnTrip, int idCityFrom, int idCityTo, String description, short price, Integer idCars, short sitNumber, String sizeOfLuggage) {
		this.id = id;
		this.dateFirstTrip = dateFirstTrip;
		this.dateReturnTrip = dateReturnTrip;
		this.idCityFrom = idCityFrom;
		this.idCityTo = idCityTo;
		this.description = description;
		this.price = price;
		this.idCars = idCars;
		this.sitNumber = sitNumber;
		this.sizeOfLuggage = sizeOfLuggage;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCovoiturage", column = @Column(name = "id_covoiturage", nullable = false) ),
			@AttributeOverride(name = "idPreference", column = @Column(name = "id_preference", nullable = false) ) })
	public CovoiturageId getId() {
		return this.id;
	}

	public void setId(CovoiturageId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_first_trip", length = 13)
	public Date getDateFirstTrip() {
		return this.dateFirstTrip;
	}

	public void setDateFirstTrip(Date dateFirstTrip) {
		this.dateFirstTrip = dateFirstTrip;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_return_trip", nullable = false, length = 13)
	public Date getDateReturnTrip() {
		return this.dateReturnTrip;
	}

	public void setDateReturnTrip(Date dateReturnTrip) {
		this.dateReturnTrip = dateReturnTrip;
	}

	@Column(name = "id_city_from", nullable = false)
	public int getIdCityFrom() {
		return this.idCityFrom;
	}

	public void setIdCityFrom(int idCityFrom) {
		this.idCityFrom = idCityFrom;
	}

	@Column(name = "id_city_to", nullable = false)
	public int getIdCityTo() {
		return this.idCityTo;
	}

	public void setIdCityTo(int idCityTo) {
		this.idCityTo = idCityTo;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false)
	public short getPrice() {
		return this.price;
	}

	public void setPrice(short price) {
		this.price = price;
	}

	@Column(name = "id_cars")
	public Integer getIdCars() {
		return this.idCars;
	}

	public void setIdCars(Integer idCars) {
		this.idCars = idCars;
	}

	@Column(name = "sit_number", nullable = false)
	public short getSitNumber() {
		return this.sitNumber;
	}

	public void setSitNumber(short sitNumber) {
		this.sitNumber = sitNumber;
	}

	@Column(name = "size_of_luggage", nullable = false)
	public String getSizeOfLuggage() {
		return this.sizeOfLuggage;
	}

	public void setSizeOfLuggage(String sizeOfLuggage) {
		this.sizeOfLuggage = sizeOfLuggage;
	}

}
