package kaszucar.model;
// Generated 15 mars 2016 00:08:54 by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Opinion generated by hbm2java
 */
@Entity
@Table(name = "opinion", schema = "public")
public class Opinion implements java.io.Serializable {


  private int idOpinion;
  private Users usersByIdUsersTo;
  private Users usersByIdUsersFrom;
  private String description;
  private int score;

  public Opinion() {}


  public Opinion(int idOpinion, Users usersByIdUsersTo, Users usersByIdUsersFrom, int score) {
    this.idOpinion = idOpinion;
    this.usersByIdUsersTo = usersByIdUsersTo;
    this.usersByIdUsersFrom = usersByIdUsersFrom;
    this.score = score;
  }

  public Opinion(int idOpinion, Users usersByIdUsersTo, Users usersByIdUsersFrom,
      String description, int score) {
    this.idOpinion = idOpinion;
    this.usersByIdUsersTo = usersByIdUsersTo;
    this.usersByIdUsersFrom = usersByIdUsersFrom;
    this.description = description;
    this.score = score;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id_opinion", unique = true, nullable = false)
  public int getIdOpinion() {
    return this.idOpinion;
  }

  public void setIdOpinion(int idOpinion) {
    this.idOpinion = idOpinion;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_users_to", nullable = false)
  public Users getUsersByIdUsersTo() {
    return this.usersByIdUsersTo;
  }

  public void setUsersByIdUsersTo(Users usersByIdUsersTo) {
    this.usersByIdUsersTo = usersByIdUsersTo;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_users_from", nullable = false)
  public Users getUsersByIdUsersFrom() {
    return this.usersByIdUsersFrom;
  }

  public void setUsersByIdUsersFrom(Users usersByIdUsersFrom) {
    this.usersByIdUsersFrom = usersByIdUsersFrom;
  }


  @Column(name = "description")
  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Column(name = "score", nullable = false)
  public int getScore() {
    return this.score;
  }

  public void setScore(int score) {
    this.score = score;
  }



}


