package kaszucar.model;
// Generated 11 f�vr. 2016 09:50:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Preference generated by hbm2java
 */
@Entity
@Table(name = "preference", schema = "public")
public class Preference implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idPreference;
	private Boolean smoking;
	private Boolean animals;
	private Boolean musics;
	private Boolean detour;
	private Boolean food;

	public Preference() {
	}

	public Preference(int idPreference) {
		this.idPreference = idPreference;
	}

	public Preference(int idPreference, Boolean smoking, Boolean animals, Boolean musics, Boolean detour, Boolean food) {
		this.idPreference = idPreference;
		this.smoking = smoking;
		this.animals = animals;
		this.musics = musics;
		this.detour = detour;
		this.food = food;
	}

	@Id

	@Column(name = "id_preference", unique = true, nullable = false)
	public int getIdPreference() {
		return this.idPreference;
	}

	public void setIdPreference(int idPreference) {
		this.idPreference = idPreference;
	}

	@Column(name = "smoking")
	public Boolean getSmoking() {
		return this.smoking;
	}

	public void setSmoking(Boolean smoking) {
		this.smoking = smoking;
	}

	@Column(name = "animals")
	public Boolean getAnimals() {
		return this.animals;
	}

	public void setAnimals(Boolean animals) {
		this.animals = animals;
	}

	@Column(name = "musics")
	public Boolean getMusics() {
		return this.musics;
	}

	public void setMusics(Boolean musics) {
		this.musics = musics;
	}

	@Column(name = "detour")
	public Boolean getDetour() {
		return this.detour;
	}

	public void setDetour(Boolean detour) {
		this.detour = detour;
	}

	@Column(name = "food")
	public Boolean getFood() {
		return this.food;
	}

	public void setFood(Boolean food) {
		this.food = food;
	}

}
