package kaszucar.model;
// Generated 15 mars 2016 00:08:54 by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersHasCovoiturage generated by hbm2java
 */
@Entity
@Table(name = "users_has_covoiturage", schema = "public")
public class UsersHasCovoiturage implements java.io.Serializable {


  private int idUsersHasCovoiturage;
  private Covoiturage covoiturage;
  private Users users;

  public UsersHasCovoiturage() {}

  public UsersHasCovoiturage(int idUsersHasCovoiturage, Covoiturage covoiturage, Users users) {
    this.idUsersHasCovoiturage = idUsersHasCovoiturage;
    this.covoiturage = covoiturage;
    this.users = users;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id_users_has_covoiturage", unique = true, nullable = false)
  public int getIdUsersHasCovoiturage() {
    return this.idUsersHasCovoiturage;
  }

  public void setIdUsersHasCovoiturage(int idUsersHasCovoiturage) {
    this.idUsersHasCovoiturage = idUsersHasCovoiturage;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_covoiturage", nullable = false)
  public Covoiturage getCovoiturage() {
    return this.covoiturage;
  }

  public void setCovoiturage(Covoiturage covoiturage) {
    this.covoiturage = covoiturage;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_users", nullable = false)
  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }



}


