package kaszucar.model;
// Generated 28 avr. 2016 10:22:28 by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersHasCovoiturage generated by hbm2java
 */
@Entity
@Table(name = "users_has_covoiturage", schema = "public")
public class UsersHasCovoiturage implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int idUsersHasCovoiturage;
  private Covoiturage covoiturage;
  private Users users;
  private Boolean passagers;

  public UsersHasCovoiturage() {}


  public UsersHasCovoiturage(int idUsersHasCovoiturage, Covoiturage covoiturage, Users users) {
    this.idUsersHasCovoiturage = idUsersHasCovoiturage;
    this.covoiturage = covoiturage;
    this.users = users;
  }

  public UsersHasCovoiturage(int idUsersHasCovoiturage, Covoiturage covoiturage, Users users,
      Boolean passagers) {
    this.idUsersHasCovoiturage = idUsersHasCovoiturage;
    this.covoiturage = covoiturage;
    this.users = users;
    this.passagers = passagers;
  }

  @Id

  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id_users_has_covoiturage", unique = true, nullable = false)
  public int getIdUsersHasCovoiturage() {
    return this.idUsersHasCovoiturage;
  }

  public void setIdUsersHasCovoiturage(int idUsersHasCovoiturage) {
    this.idUsersHasCovoiturage = idUsersHasCovoiturage;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_covoiturage", nullable = false)
  public Covoiturage getCovoiturage() {
    return this.covoiturage;
  }

  public void setCovoiturage(Covoiturage covoiturage) {
    this.covoiturage = covoiturage;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_users")
  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }


  @Column(name = "passagers")
  public Boolean getPassagers() {
    return this.passagers;
  }

  public void setPassagers(Boolean passagers) {
    this.passagers = passagers;
  }



}


