package kaszucar.model;
// Generated 15 mars 2016 00:08:54 by Hibernate Tools 4.3.1.Final


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersHasCars generated by hbm2java
 */
@Entity
@Table(name = "users_has_cars", schema = "public")
public class UsersHasCars implements java.io.Serializable {


  private int idUsersHasCarl;
  private Cars cars;
  private Users users;

  public UsersHasCars() {}

  public UsersHasCars(int idUsersHasCarl, Cars cars, Users users) {
    this.idUsersHasCarl = idUsersHasCarl;
    this.cars = cars;
    this.users = users;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id_users_has_carl", unique = true, nullable = false)
  public int getIdUsersHasCarl() {
    return this.idUsersHasCarl;
  }

  public void setIdUsersHasCarl(int idUsersHasCarl) {
    this.idUsersHasCarl = idUsersHasCarl;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_cars", nullable = false)
  public Cars getCars() {
    return this.cars;
  }

  public void setCars(Cars cars) {
    this.cars = cars;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_users", nullable = false)
  public Users getUsers() {
    return this.users;
  }

  public void setUsers(Users users) {
    this.users = users;
  }



}


