package kaszucar.model;
// Generated 11 f�vr. 2016 09:50:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsersHasCovoiturage generated by hbm2java
 */
@Entity
@Table(name = "users_has_covoiturage", schema = "public")
public class UsersHasCovoiturage implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsersHasCovoiturageId id;

	public UsersHasCovoiturage() {
	}

	public UsersHasCovoiturage(UsersHasCovoiturageId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idUsersHasCovoiturage", column = @Column(name = "id_users_has_covoiturage", nullable = false) ),
			@AttributeOverride(name = "usersIdUsers", column = @Column(name = "users_id_users", nullable = false) ),
			@AttributeOverride(name = "covoiturageIdCovoiturage", column = @Column(name = "covoiturage_id_covoiturage", nullable = false) ) })
	public UsersHasCovoiturageId getId() {
		return this.id;
	}

	public void setId(UsersHasCovoiturageId id) {
		this.id = id;
	}

}
