package kaszucar.model;
// Generated 4 févr. 2016 18:26:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	private int idUsers;
	private String name;
	private String lastName;
	private Short phoneNumber;
	private String emailAdress;
	private String password;
	private String ipAddress;
	private Integer idAddress;
	private String genre;
	private short yearOfBirth;
	private String description;
	private String urlPicture;
	private String idAdress;
	private String ipAdress;
	private Integer phonenumber;

	public Users() {
	}

	public Users(int idUsers, String name, String lastName, String emailAdress, String password, String genre, short yearOfBirth) {
		this.idUsers = idUsers;
		this.name = name;
		this.lastName = lastName;
		this.emailAdress = emailAdress;
		this.password = password;
		this.genre = genre;
		this.yearOfBirth = yearOfBirth;
	}

	public Users(int idUsers, String name, String lastName, Short phoneNumber, String emailAdress, String password, String ipAddress, Integer idAddress, String genre, short yearOfBirth, String description, String urlPicture, String idAdress, String ipAdress, Integer phonenumber) {
		this.idUsers = idUsers;
		this.name = name;
		this.lastName = lastName;
		this.phoneNumber = phoneNumber;
		this.emailAdress = emailAdress;
		this.password = password;
		this.ipAddress = ipAddress;
		this.idAddress = idAddress;
		this.genre = genre;
		this.yearOfBirth = yearOfBirth;
		this.description = description;
		this.urlPicture = urlPicture;
		this.idAdress = idAdress;
		this.ipAdress = ipAdress;
		this.phonenumber = phonenumber;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_users", unique = true, nullable = false)
	public int getIdUsers() {
		return this.idUsers;
	}

	public void setIdUsers(int idUsers) {
		this.idUsers = idUsers;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "phone_number", unique = true)
	public Short getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Short phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "email_adress", unique = true, nullable = false)
	public String getEmailAdress() {
		return this.emailAdress;
	}

	public void setEmailAdress(String emailAdress) {
		this.emailAdress = emailAdress;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ip_address", length = 15)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "id_address")
	public Integer getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(Integer idAddress) {
		this.idAddress = idAddress;
	}

	@Column(name = "genre", nullable = false, length = 3)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Column(name = "year_of_birth", nullable = false)
	public short getYearOfBirth() {
		return this.yearOfBirth;
	}

	public void setYearOfBirth(short yearOfBirth) {
		this.yearOfBirth = yearOfBirth;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url_picture", length = 1024)
	public String getUrlPicture() {
		return this.urlPicture;
	}

	public void setUrlPicture(String urlPicture) {
		this.urlPicture = urlPicture;
	}

	@Column(name = "id_adress")
	public String getIdAdress() {
		return this.idAdress;
	}

	public void setIdAdress(String idAdress) {
		this.idAdress = idAdress;
	}

	@Column(name = "ip_adress")
	public String getIpAdress() {
		return this.ipAdress;
	}

	public void setIpAdress(String ipAdress) {
		this.ipAdress = ipAdress;
	}

	@Column(name = "phonenumber")
	public Integer getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(Integer phonenumber) {
		this.phonenumber = phonenumber;
	}

}
