package kaszucar.model;
// Generated 4 févr. 2016 18:26:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersHasCovoiturageId generated by hbm2java
 */
@Embeddable
public class UsersHasCovoiturageId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idUsersHasCovoiturage;
	private int usersIdUsers;
	private int covoiturageIdCovoiturage;

	public UsersHasCovoiturageId() {
	}

	public UsersHasCovoiturageId(int idUsersHasCovoiturage, int usersIdUsers, int covoiturageIdCovoiturage) {
		this.idUsersHasCovoiturage = idUsersHasCovoiturage;
		this.usersIdUsers = usersIdUsers;
		this.covoiturageIdCovoiturage = covoiturageIdCovoiturage;
	}

	@Column(name = "id_users_has_covoiturage", nullable = false)
	public int getIdUsersHasCovoiturage() {
		return this.idUsersHasCovoiturage;
	}

	public void setIdUsersHasCovoiturage(int idUsersHasCovoiturage) {
		this.idUsersHasCovoiturage = idUsersHasCovoiturage;
	}

	@Column(name = "users_id_users", nullable = false)
	public int getUsersIdUsers() {
		return this.usersIdUsers;
	}

	public void setUsersIdUsers(int usersIdUsers) {
		this.usersIdUsers = usersIdUsers;
	}

	@Column(name = "covoiturage_id_covoiturage", nullable = false)
	public int getCovoiturageIdCovoiturage() {
		return this.covoiturageIdCovoiturage;
	}

	public void setCovoiturageIdCovoiturage(int covoiturageIdCovoiturage) {
		this.covoiturageIdCovoiturage = covoiturageIdCovoiturage;
	}

	public boolean equals(Object other) {
		if ((this == other)) return true;
		if ((other == null)) return false;
		if (!(other instanceof UsersHasCovoiturageId)) return false;
		UsersHasCovoiturageId castOther = (UsersHasCovoiturageId) other;

		return (this.getIdUsersHasCovoiturage() == castOther.getIdUsersHasCovoiturage())
				&& (this.getUsersIdUsers() == castOther.getUsersIdUsers())
				&& (this.getCovoiturageIdCovoiturage() == castOther.getCovoiturageIdCovoiturage());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsersHasCovoiturage();
		result = 37 * result + this.getUsersIdUsers();
		result = 37 * result + this.getCovoiturageIdCovoiturage();
		return result;
	}

}
